Error from server (AlreadyExists): pods "udacity-microservices-espeon" already exists
NAME                           READY   STATUS    RESTARTS   AGE
udacity-microservices-espeon   1/1     Running   0          70s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}

[2023-10-12 19:22:31,414] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-10-12 19:22:31,425] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-10-12 19:22:31,429] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-10-12 19:22:31,433] INFO in app: The output prediction is:
[20.35373177134412]
172.17.0.1 - - [12/Oct/2023 19:22:31] "POST /predict HTTP/1.1" 200 -